import { Inter } from "next/font/google";
import "./globals.css";
import ClientProviders from './ClientProviders';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Unicapp | Best Delivery Service",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ backgroundColor: '#F1EDEA', height: '100%' }}>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link id="favicon" rel="icon" type="ico" href="favicon.ico" />
        <link rel="manifest" href="/site.webmanifest" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              function updateFavicon() {
                const favicon = document.getElementById('favicon');
                const darkScheme = window.matchMedia('(prefers-color-scheme: dark)');

                if (darkScheme.matches) {
                  favicon.href = 'favicon-dark.ico';
                } else {
                  favicon.href = 'favicon.ico';
                }
              }

              updateFavicon();

              window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', updateFavicon);
            `,
          }}
        />
      </head>
      <body className={inter.className}>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
